services:
  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 200 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local